INSERT INTO `users` (`name`)
VALUES ("Ignore"),
       ("Uma"),
       ("John"),
       ("Tad"),
       ("Asher"),
       ("Quon"),
       ("Solomon"),
       ("Lillith"),
       ("Emerson"),
       ("Xyla"),
       ("Vaughan"),
       ("Freya"),
       ("Vernon"),
       ("Phoebe"),
       ("Chadwick"),
       ("Zahir"),
       ("Lillian"),
       ("Dylan"),
       ("Burton"),
       ("Angela");

INSERT INTO `exams` (`name`, `level`)
VALUES ("Mid-Term Exam", 2),
       ("Final Exam", 1),
       ("Pop Quiz", 3),
       ("Mid-Term Exam", 2),
       ("Final Exam", 1),
       ("Mid-Term Exam", 2),
       ("Final Exam", 1),
       ("Mid-Term Exam", 2),
       ("Final Exam", 1);

INSERT INTO `scores` (`user_id`, `exam_id`, `score`)
VALUES (1, 1, 0),
       (2, 2, 100),
       (1, 2, 70),
       (4, 1, 50),
       (3, 1, 0),
       (15, 7, 55),
       (5, 8, 80),
       (7, 2, 40),
       (3, 4, 100),
       (5, 5, 65),
       (5, 6, 80),
       (5, 9, 70),
       (13, 3, 79),
       (8, 3, 90),
       (1, 3, 98),
       (2, 1, 90);
